apiVersion: v1
kind: Namespace
metadata:
  name: minecharts
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minecharts
  namespace: minecharts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minecharts
  namespace: minecharts
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "get", "list", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["traefik.io", "traefik.containo.us"]
    resources: ["ingressroutetcps", "ingressroutes"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minecharts
  namespace: minecharts
subjects:
  - kind: ServiceAccount
    name: minecharts
    namespace: minecharts
roleRef:
  kind: Role
  name: minecharts
  apiGroup: rbac.authorization.k8s.io
